blank_issues_enabled: false
contact_links:
  - name: Documentation / Usage / FAQ
    url: https://ultimate-notion.com/
    about: Inform yourself about the usage of Ultimate-Notion on the official website
  - name: Discussions
    url: https://github.com/ultimate-notion/ultimate-notion/discussions
    about: Ask questions, find answers and discuss with other Ultimate-Notion community members
